name: Release tool and DB

on:
  release:
    types: [released]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Release Tag
        id: make_context
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.19
          dest: build
          prefix: tn-feeder
          targets: darwin/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: true
          x: true
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true

      - name: Compress
        run: |
          echo '### Compress' >> $$GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          upx ./build/* >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Compression completed, result: \`$(du -h ./build/*)\`" >> $GITHUB_STEP_SUMMARY

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Executables
          path: ./build/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          append_body: true
          files: |
            ./build/tn-feeder-linux-amd64
            ./build/tn-feeder-linux-arm64
            ./build/tn-feeder-darwin-amd64
            ./build/tn-feeder-darwin-arm64
        env:
          GITHUB_REPOSITORY: infinimesh/tn_fake_feeder
