name: Release tool and DB

on:
  release:
    types: [released]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, darwin/amd64, darwin/arm64
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - name: Check Release Tag
        id: make_context
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.19
          dest: build
          targets: darwin/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true

      - name: Debug
        run: echo "### Build Result" >> $GITHUB_STEP_SUMMARY
          echo $(ls -lh build) >> $GITHUB_STEP_SUMMARY

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     append_body: true
      #   env:
      #     GITHUB_REPOSITORY: infinimesh/tn_fake_feeder

      # - uses: wangyoucao577/go-release-action@v1.29
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     goos: ${{ matrix.goos }}
      #     goarch: ${{ matrix.goarch }}
      #     overwrite: true
      #     goversion: 1.19
      #     ldflags: -s -w
      #     executable_compression: upx
      #     project_path: .
      #     binary_name: "tn-feeder"
      #     extra_files: track.db README.md
